### ISSUE TITLE
weex-loader计算容器高度有误

### ISSUE THREAD

**Issue by iceyao** [apache/incubator-weex-loader#12]
同样的内容，通过weex-loader和weex-toolkit编译出来产出的内容容器高度是不一致的，weex-toolkit编译产出高度符合预期，能正常滚动；weex-loader编译产出高度偏差严重，导致内容高度低于外层容器高度而不能滚动。

**Comment by Jinjiang** [comment]
可以提供一个例子吗？方便我们排查定位
谢谢

**Comment by terrykingcha** [comment]
没有进一步的内容，暂时关闭。如果题主继续有问题，可以重开或新开。
