### ISSUE TITLE
[bug]weex-loader@0.3.0-alpha无法加载独立css文件

### ISSUE THREAD

**Issue by SimonTal** [apache/incubator-weex-loader#14]
先前版本的weex-loader（v0.2.3）能够正确加载独立css文件，而0.3.0-alpha在处理过程中 会提示 template区块找不到，然后就无法正确输出js文件了，忘排查解决，谢谢！

**Comment by Jinjiang** [comment]
理论上 `*.we` 文件必须包含 `<template>`，另外新版独立加载样式的方式其实是有区别的，可能需要有劳您具体看一下文档
这里我先关掉了，如果还有问题我们可以随时回复讨论

谢谢
