### ISSUE TITLE
js文件无法打包内部模块

### ISSUE THREAD

**Issue by Jango26** [apache/incubator-weex-loader#18]
在.js文件里require核心模块，比如

``` javascript
var mtop = require('@weex-module/mtop');
```

打包后，输出错误
![](https://img.alicdn.com/tps/TB1PokNMVXXXXbvaXXXXXXXXXXX-884-69.png)

**Comment by terrykingcha** [comment]
请参考这里的解决方案：https://github.com/alibaba/weex/blob/dev/doc/specs/js-bundle-format.md#__weex_require__name-string-object
