### ISSUE TITLE
style标签在引用公共css的同时，如何在we文件中再自定义一些style样式

### ISSUE THREAD

**Issue by qbcbyb** [apache/incubator-weex-loader#20]
在`0.2.*`版本的时候，可以一下通过这种方式引用公共的css样式，同时还可以继续写`<style></style>`定义一些内部样式。

```
<script>
    require('weex-components');
    module.exports = {
        style: require('../css/common.css'),
    ...
```

现在升级成了0.3.1后，虽然可以通过`<style src="./css/common.css"></style>`引用外部样式文件，但没法同时再在we文件中定义`<style></style>`的样式了，试了很多办法，都没法将外部css和内部css共存。  
请问有什么办法可以实现我说的这种需求吗？

**Comment by terrykingcha** [comment]
0.3.1版本中，无法达到你提的需求，也并没有觉得内联和外联的方式共存会带来多大的好处。所以，暂时不会再考虑加入对这个特性的支持。
