### ISSUE TITLE
`0.3.2` 版本 dependencies 变动问题

### ISSUE THREAD

**Issue by hirokith** [apache/incubator-weex-loader#24]
`0.3.2` 版本开始把 `babel-plugin-transform-runtime` 从 devDependencies 挪到 dependencies，但是如果在项目下 `package.json` 里已经有了 `babel-plugin-transform-runtime` 的 devDependencies 的依赖，就会导致 `npm install` 之后，`weex-loader` 下的 `node_modules` 目录下其实并不存在 `babel-plugin-transform-runtime` 而是位于项目目录的 `node_modules` 目录下，
导致 https://github.com/weexteam/weex-loader/blob/master/src/loader.js#L136 报错。

解决办法：当加载 `babel-plugin-transform-runtime` 失败时需要同时检查 `path.join(process.cwd(), 'node_modules')` 下是否存在 `babel-plugin-transform-runtime`

**Comment by mtyang** [comment]
babel-plugin-transform-runtime
babel-preset-es2015

这两个包都有变动

**Comment by hanai** [comment]
挺奇怪的是为什么要把 babel 的设置写在代码里而不是在外置的 `.babelrc` 配置?
