### ISSUE TITLE
支持多个 <style> 标签

### ISSUE THREAD

**Issue by Hanks10100** [apache/incubator-weex-loader#29]
目前如果存在多个 `<style>` 标签只有第一个生效，希望能够支持多个 `<style>` 的样式同时生效，靠后的样式会覆盖前面的。

考虑添加这个功能的原因是：
### 方便多个组件共享样式

目前 `<style>` 标签支持 `src` 属性，能够从 CSS 文件读取样式。不过使用 `src` 属性后，内部定义的样式会被忽略（这个特性没有问题）。如果想实现多个组件能使用公共样式，可以有如下写法：

``` html
<style src="../css/common.css"></style>

<style>
  .specific {
    font-size: 66
  }
</style>
```
### 能针对平台写样式

可以实现针对不同平台、横竖屏幕写样式。目前 weex 没有这个功能，后期会考虑加入这种特性。

``` html
<style platform="desktop">
  .banner {
    height: 80;
  }
</style>

<style platform="mobile" orientation="portrait">
  .banner {
    font-size: 45;
  }
</style>

<style platform="tablet" orientation="landscape">
  .banner {
    color: blue;
  }
</style>
```

**Comment by Jinjiang** [comment]
针对平台可以借鉴一下 media query 的语法

**Comment by Jam1zhu** [comment]
<img width="401" alt="2016-09-30 10 30 27" src="https://cloud.githubusercontent.com/assets/21252750/18981519/b36d3f88-8711-11e6-8f1d-9b9aac9fe283.png">
@Hanks10100  这样还是只显示第一个style里的样式，第二个不现实，什么原因呐？

**Comment by Hanks10100** [comment]
@Jam1zhu 现在还不支持多个 `<style>` 标签，只是个提议。

**Comment by terrykingcha** [comment]
不建议，可以通过引用单独的css文件，并且在这个css文件里进行import，来达到目的。实在想不出写多几个style标签有什么必须场景。

**Comment by Hanks10100** [comment]
@terrykingcha 嗯，如果不支持多个 `<style>` 标签的话可以考虑支持 `import` 和 `media query` 的写法。

**Comment by esmeetu** [comment]
现在支持在`<style>`里用`import`导入外部样式了吗？另外`<style lang="stylus">"`支持吗？

**Comment by Hanks10100** [comment]
@esmeetu 还不支持

**Comment by terrykingcha** [comment]
@esmeetu 自定义lang的方法，请参考READMD里的相关描述 https://github.com/weexteam/weex-loader#add-some-custom-language-for-loaders

**Comment by hirokith** [comment]
media query 的写法目前有什么设计思路了吗？我想通过一些语法糖加上 webpack loader 来解决，但很遗憾的是发现 `weex-loader` 其实是比较封闭的，也就是我的 loader 配置在 `preLoaders` 里面对 `.we` 源码做了一些预处理，但是到了 `weex-loader` 里是会生成

```
var __weex_script__ = require("!!./node_modules/weex-loader/lib/script.js!babel-loader?presets[]=./wxc-component/node_modules/babel-preset-es2015&presets=./wxc-component/node_modules/babel-preset-es2015&plugins[]=./wxc-component/node_modules/weex-loader/node_modules/babel-plugin-transform-runtime&plugins=./wxc-component/node_modules/weex-loader/node_modules/babel-plugin-transform-runtime&comments=false!./node_modules/weex-loader/lib/extract.js?index=0&type=scripts!./index.we")
```

这样的代码，也就是仍然从原始的 `.we` 文件 parse，也就意味着其实第三方的 loader 其实没法做一些预处理。

**Comment by Jinjiang** [comment]
@dickeylth 恩，将来基于 Vue 2.0 的 loader 可以写多个 style 标签或文件，也支持方言和预处理的 loader 的扩展，现在 `weex-loader@0.4.x` 已经可以处理 `*.vue` 文件了，并可以配合 Vue 2.0 在 Weex 上工作

**Comment by feishu** [comment]
@Jinjiang 将来 还要多久呢？还是用VUE已经可以用STYLE多标签了吗 或者import

**Comment by Jinjiang** [comment]
现在已经可以了

**Comment by feishu** [comment]
如果我们要使用多个STYLE需要怎么做呢

**Comment by Jinjiang** [comment]
在 *.vue 文件中现在直接写多个 `<style>` 标签就已经可以了，`*.we` 我们不打算增加这个特性了，鼓励大家使用或尽可能迁移到 Vue 2.0，团队也希望在 Vue 2.0 上多花一些时间，希望理解。
这个 issue 我关掉了
