### ISSUE TITLE
[Proposal] Support original `define` and `require`

### ISSUE THREAD

**Issue by Hanks10100** [apache/incubator-weex-loader#34]
Currently, `weex-loder` will generate `__weex_define__` instead of the original `define`. But the old version of weex js framework doesn't support this variable.

+ `__weex_define__` is supported since *v0.13.8*.
+ `__weex_bootstrap__` is supported since *v0.13.8*.
+ `__weex_require__` is supported since *v0.15.3*.

The js bundle generated by `weex-loader` couldn't run on js framework below v0.13.8. This problem should be fixed to improve the compatibility.

**Comment by Jinjiang** [comment]
My suggestion is old version js framework could work with old version weex-loader.

**Comment by Jinjiang** [comment]
`define` and `require` is recommended to be preserved keywords for other 3rd-party packaging tools. That's why we give up them in new version.

**Comment by Hanks10100** [comment]
Does it possible to support both `define` and `__weex_define__` at the same time ? If the loader can't achieve it, at least should provide an configuration or specific version to do this.

**Comment by Jinjiang** [comment]
It's not recommended. What we should do is encourage people use latest version, not do more things for the past.
