### ISSUE TITLE
Discuss new weex-loader 

### ISSUE THREAD

**Issue by terrykingcha** [apache/incubator-weex-loader#7]

**Comment by JerroldLee** [comment]
weex-loader升级到0.3.0-alpha后，原来所有的js文件都报“Template block is required”错误，怎么解决？

**Comment by terrykingcha** [comment]
@JerroldLee weex-loader@0.3.0-alpha，不再支持老版分开文件的方式。新的分开文件的方式如下：

**main.we**

``` html
<template src="./main.html"></template>
<style src="./main.css"></style>
<script src="./main.js"></script>
```

**main.html**

``` html
<div><text class="txt">Hello {{name}}</text></div>
```

**main.css**

``` css
.txt {
  color: red;
}
```

**main.js**

``` javascript
module.exports = {
  data: function() {
     return  {
         name: 'Weex'
     }
  }
}
```

或参考[Spec:Build from parted files specifed in src attr](https://github.com/weexteam/weex-loader/blob/dev/test/spec/f.we)

**Comment by JerroldLee** [comment]
我拆成这个的结构还是报“Template block is required”错误

**Comment by JerroldLee** [comment]
跟webpack的配置有关吗？
`module.exports = {
  entry: entry,
  output : {
    path: '.',
    filename: '[name].js'
  },
  module: {
    loaders: [
      {
        test: /\.we(\?[^?]+)?$/,
        loader: 'weex'
      },
      {
        test: /\.js(\?[^?]+)?$/,
        loader: 'weex?type=script'
      },
      {
        test: /\.css(\?[^?]+)?$/,
        loader: 'weex?type=style'
      }, 
      {
        test: /\.html(\?[^?]+)?$/,
        loader: 'weex?type=tpl'
      }
    ]
  }
}`

**Comment by JerroldLee** [comment]
webpack.config.js只保留.we后会报Module not found: Error: Cannot resolve module ‘@weex-module/stream’ 之类的错误

**Comment by terrykingcha** [comment]
能把你出这个错的，最小代码粘贴一下我看下吗？

**Comment by JerroldLee** [comment]
聊天室里发的那些你看到了吗

**Comment by hanai** [comment]
现在好些we文件里是没有template标签的，比如 weex-components/index.we 内容如下，

``` html
<script>
  require('./src/wxc-button.we');
  require('./src/wxc-hn.we');
  require('./src/wxc-list-item.we');
  require('./src/wxc-panel.we');
  require('./src/wxc-tip.we');
  require('./src/wxc-countdown.we');
  require('./src/wxc-marquee.we');
  require('./src/wxc-navbar.we');
  require('./src/wxc-navpage.we');
  require('./src/wxc-tabbar.we');
  require('./src/wxc-tabitem.we');
</script>
```

强制检查 template 标签的话会导致这些都没办法使用了

所以希望把对template标签的检查去掉。

**Comment by Jinjiang** [comment]
@hanai 准确的写法应该是 `index.js` 文件，里面内容：

``` js
  require('./src/wxc-button.we');
  require('./src/wxc-hn.we');
  require('./src/wxc-list-item.we');
  require('./src/wxc-panel.we');
  require('./src/wxc-tip.we');
  require('./src/wxc-countdown.we');
  require('./src/wxc-marquee.we');
  require('./src/wxc-navbar.we');
  require('./src/wxc-navpage.we');
  require('./src/wxc-tabbar.we');
  require('./src/wxc-tabitem.we');
```

`weex-components@0.2.0` 的主文件已经是 `index.js` 了

p.s. 刚才误操作把 issue 关了，现在已经 reopen 请见谅

**Comment by lmnsg** [comment]
weex-loader 如何使用 webpack 自定义 babel option 以及如何使用 babel 的 Promise polyfill 呢？

**Comment by terrykingcha** [comment]
@Imnsg 请参考[自定义lang的方式](https://github.com/weexteam/weex-loader#add-some-custom-language-for-loaders)

**Comment by Hanks10100** [comment]
Closed, because it's out of date.
