### ISSUE TITLE
JavaScript file error: "Template block is required"

### ISSUE THREAD

**Issue by Jinjiang** [apache/incubator-weex-loader#8]
weex-loader升级到0.3.0-alpha后，原来所有的js文件都报“Template block is required”错误，怎么解决？ https://github.com/alibaba/weex/issues/827 @JerroldLee

**Comment by xubodreamsky** [comment]
同问，npm run build 会报错

**Comment by Jinjiang** [comment]
@xubodreamsky 请提供一下你的 npm 包版本和导致报错的前端代码
谢谢
